"""Initial migration

Revision ID: 500a38c45250
Revises: 4f082e723375
Create Date: 2025-01-03 20:27:52.169949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '500a38c45250'
down_revision: Union[str, None] = '4f082e723375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('selected_public_file_ids', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'selected_public_file_ids')
    # ### end Alembic commands ###
